version: "2"

services:
  mongodb:
    image: "mongo"
    expose:
      - '27017'
    ports:
      - '27017:27017'

  backend:
    build:  ./backend/
    expose:
      - '5000'
    ports: 
      - "5000:5000"
    volumes:
      - ./backend:/app
    depends_on: 
      - mongodb
    links:
      - mongodb
  
  frontend:
    build: ./frontend/
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on: 
      - backend
    links:
      - backend