version: "2"

services:
  mongodb:
    container_name: mongodb
    image: "mongo"
    ports:
      - '27017:27017'

  backend:
    container_name: backend
    build:  ./backend/
    ports: 
      - "5000:5000"
    depends_on: 
      - mongodb
    links:
      - mongodb
  
  frontend:
    container_name: frontend
    build: ./frontend/
    ports:
      - "3000:3000"
    depends_on: 
      - backend
    links:
      - backend